(put 'downcase-region 'disabled nil)
(put 'upcase-region 'disabled nil)

(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(CUA-mode-overwrite-cursor-color "black")
 '(CUA-mode-read-only-cursor-color "red")
 '(bar-cursor-mode t nil (bar-cursor))
 '(brew-emulator "c:/brew/v30/sdk/bin/BREW_Simulator.exe")
 '(browse-url-browser-function (quote browse-url-default-browser))
 '(c-basic-offset 4)
 '(c-default-style "stroustrup")
 '(calculator-electric-mode t)
 '(calculator-number-digits 10)
 '(case-fold-search t)
 '(compilation-ask-about-save nil)
 '(compilation-scroll-output t)
 '(current-language-environment "English")
 '(cursor-in-non-selected-windows nil)
 '(custom-file "~/.emacs.d/custom.el")
 '(default-frame-alist (quote ((vertical-scroll-bars . right) (tool-bar-lines . 0) (menu-bar-lines . 1) (width . 131) (height . 58))))
 '(ecb-compilation-buffer-names (quote (("*Calculator*") ("*vc*") ("*vc-diff*") ("*Apropos*") ("*Occur*") ("*shell*") ("\\*[cC]ompilation.*\\*" . t) ("\\*i?grep.*\\*" . t) ("*JDEE Compile Server*") ("*Help*") ("*Completions*") ("*Backtrace*") ("*Compile-log*") ("*bsh*") ("*Messages*") ("*slime-repl[1]*") ("*compiler notes*"))))
 '(ecb-compile-window-height 10)
 '(ecb-compile-window-temporally-enlarge nil)
 '(ecb-compile-window-width (quote edit-window))
 '(ecb-layout-name "right1")
 '(ecb-options-version "2.27")
 '(ecb-primary-secondary-mouse-buttons (quote mouse-1--C-mouse-1))
 '(ecb-source-path (quote ("~/development")))
 '(ecb-tip-of-the-day nil)
 '(ecb-windows-width 0.2)
 '(ediff-split-window-function (quote split-window-horizontally))
 '(ediff-window-setup-function (quote ediff-setup-windows-plain))
 '(emacs-lisp-mode-hook (quote (turn-on-eldoc-mode)))
 '(face-font-selection-order (quote (:height :width :weight :slant)))
 '(flyspell-sort-corrections t)
 '(focus-follows-mouse t)
 '(global-font-lock-mode t nil (font-lock))
 '(ielm-mode-hook (quote ((lambda nil (eldoc-mode 1)))))
 '(ilisp-*use-fsf-compliant-keybindings* t)
 '(ilisp-bindings-*bind-right-bracket-p* t)
 '(inhibit-startup-message t)
 '(mouse-autoselect-window t)
 '(nxml-slash-auto-complete-flag t)
 '(scroll-bar-mode (quote right))
 '(show-paren-mode t nil (paren))
 '(show-paren-style (quote expression))
 '(speedbar-supported-extension-expressions (quote (".[ch]\\(\\+\\+\\|pp\\|c\\|h\\|xx\\)?" ".tex\\(i\\(nfo\\)?\\)?" ".el" ".emacs" ".l" ".lsp" ".lisp" ".lml" ".p" ".java" ".f\\(90\\|77\\|or\\)?" ".ada" ".p[lm]" ".tcl" ".m" ".scm" ".pm" ".py" ".g" ".s?html" "[Mm]akefile\\(\\.in\\)?" ".xml")))
 '(tab-stop-list (quote (4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80)))
 '(tab-width 4)
 '(transient-mark-mode t)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(url-privacy-level (quote paranoid))
 '(w3m-favicon-use-cache-file t)
 '(w3m-use-tab nil)
 '(x-select-enable-clipboard t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 )
